### PR TITLE
add custom json converter for capabilities fields

### PR DESCRIPTION
**Pull request by polushinmk**
custom string to bool converter for capabilities fields #147

### CODE REVIEW

**Comment by ThomasPe** [comment]
will this correctly convert "1" into true? I've not yet worked with `Convert.ToBoolean`, perhaps we could add a unit test for the converter.

**Comment by polushinmk** [comment]
I tested it on data from #147 and it worked correctly, but I agree, that we should test it in more cases. I`l write some tests later

**Comment by polushinmk** [comment]
I added some tests. I don't know how representative they are, but they work :)

**Comment by ThomasPe** [comment]
well they do test the issue at hand, so I'm good with that. Thanks!

**Pull request merged**
