### PR TITLE
Added Categories methods and tests

### PR DESCRIPTION
**Pull request by CDrosos**

### CODE REVIEW

**Comment by ThomasPe** [comment]
hey, thanks for merging.
I checked out your PR but wasn't able to Build it. There seem to be some JSON.NET usings missing. Also, I get these errors:
```
Error	CS0101	The namespace 'WordPressPCL.Models' already contains a definition for 'OrderBy'	
Error	CS0101	The namespace 'WordPressPCL.Models' already contains a definition for 'Order'
```

can you repro those?

**Comment by CDrosos** [comment]
i think WordPressPCL/Models/Post.cs orderby conflicts with WordPressPCL/Models/Category.cs orderby but we need both

**Comment by polushinmk** [comment]
I think that after merging reorg-methods to master branch e61eb914e707eb9889e2d4e2146d779362ecb822 this PR in not longer actual

**Comment by ThomasPe** [comment]
my plan is to merge this PR and publish one last nuget package for this branch.
Afterwards I'll merge the reorg when I finished adding the missing tests and will publish the first beta-package.

**Comment by CDrosos** [comment]
i hope i dont create more problems than the ones i slove with my misunderstanding :)

**Comment by ThomasPe** [comment]
No worries, I'm glad people are interested in this project and willing to contribute.

**Comment by polushinmk** [comment]
@ThomasPe but in commit e61eb914e707eb9889e2d4e2146d779362ecb822 you already merged reorg-methods and master branch. Without few last commits, but with Categories implementation too. Isnt it?

**Comment by ThomasPe** [comment]
I think this was by mistake 😜
I'll try to sort things out this week.

**Comment by ThomasPe** [comment]
Turns out it was easier to just finish the reorg, which unfortunately makes your work obsolete :-(
Thanks though, I hope this new version will help you out either way.
Still, feel free to keep contributing! The smaller the PRs, the easier it is for me to integrate ;-)

**Pull request closed without merging**
