### PR TITLE
Add processing Function helper for http response string from wordpress

### PR DESCRIPTION
**Pull request by mathieumack**
The goal is to be able to add a pre processing function that will be called on rest api response strings before deserialize content string to Post, Category or others items.
Ex: Issue #44 
When WordPress is deployed on Microsoft Azure, the response contains a html code before the json content. With the preprocessing function, we can remove the html content to keep only json string.

### CODE REVIEW

**Comment by ThomasPe** [comment]
thanks  for the PR - this does look usefull. 
Could you please add some tests (best create a new test class) and maybe some documentation on what to do with the Azure problem as a new Wiki page?

**Comment by mathieumack** [comment]
Ok, I will add it today.

**Comment by mathieumack** [comment]
Unit test added. Say me if it's ok for you. It's difficult to do it in a new class. I hope it's ok.
I will create a Wiki page in the afternoon.

**Comment by mathieumack** [comment]
I can't create a new page on your repository, could you send me an invitation to this repo ?

**Comment by polushinmk** [comment]
Seems to be usefull hook.
I think, that we can implement default function for IIS hostings and add parameter to HttpHelper like useIIS which will use theese realization for IIS hostings

**Comment by ThomasPe** [comment]
Good PR - unfortunately the 1.1 merge brought some conflicts. If you can fix those, I'll gladly merge this for 1.1.1

**Comment by mathieumack** [comment]
Ok.
I will merge it tomorrow.
How can I create a wiki page on your repository ?

**Comment by ThomasPe** [comment]
I've changed the Wiki permissions, can you try if it works now?

**Comment by mathieumack** [comment]
I've created a new one PR.

**Pull request closed without merging**
