### PR TITLE
Feature/refactor url handling

### PR DESCRIPTION
**Pull request by ThomasPe**
- Updated Query Builder to use NameValueCollection
- Store WordPressUrl in httpclient as BaseUrl
- Pass defaultPath to HttpHelper so not every client needs to know about it
- Update Test Projects to .NET 6
- Change WordPressUri from string to Uri

### CODE REVIEW

**Comment by ThomasPe** [comment]
@navjot50 would like your opinion on these changes. especially the change in handling the defaultPath, think this way is a lot cleaner.

**Comment by navjot50** [comment]
@ThomasPe yes, definitely cleaner as there will be less references to the default path all over. Also, the extension methods for query params give a better way of string handling. Thumbs up from my side.

**Comment by ThomasPe** [comment]
thanks!

**Comment by ThomasPe** [comment]
https://github.com/wp-net/WordPressPCL/issues/236

**Pull request merged**
