### PR TITLE
Refactoring & Implementation of Post Types, Post Statuses, Post Revisions, Taxonomies

### PR DESCRIPTION
**Pull request by polushinmk**
Code refactoring:
- Split ICRUDOperation to 5 components:
        - IReadOperation
        - ICreateOperation
        - IUpdateOperation
        - IDeleteOperation
        - IQueryOperation
- Add abstract base class CRUPOperation which implements base operations (reduce code copypast)

New features ( #37  ):
- Implementation of Post Type
- Implementation of Post Status
- Implementation of Post Revision
- Implementation of Taxonomy
- Tests for all new features
- Update Readme

Needs review:
UX of working with revisions. I place it in Posts client class
Example:
```
var client = new WordpressClient("https://site.com/wp-json/");
var revisions = client.Posts.Revisions(postId);
var allrevisions = revisions.GetAll();
var onerevision = revisions.GetById(111);
var result = revisions.Delete(111);
```

Need tests: all after refactoring. I cannot run all tests on my site.

### CODE REVIEW

**Comment by polushinmk** [comment]
In last commits add some fixes in enums and models to be more closely connected with official docs

**Comment by ThomasPe** [comment]
There's an issue with the delete-method. Some entities need a force-parameter since they don't support trashing 

`return await _httpHelper.DeleteRequest($"{_defaultPath}{_methodPath}/{ID}?force=true").ConfigureAwait(false);`

This is needed for Tags, Users, Categories, Media & I think PostRevisions.

**Comment by polushinmk** [comment]
Hm...you are right for Tags, Users and Categories. Official WP API Handbook says that. 
Links:
- https://developer.wordpress.org/rest-api/reference/users/#delete-a-user
- https://developer.wordpress.org/rest-api/reference/tags/#delete-a-tag
- https://developer.wordpress.org/rest-api/reference/categories/#delete-a-category

But I dont find this actual for Media and Post Revisions. Did you test this?
- https://developer.wordpress.org/rest-api/reference/media/#delete-media
- https://developer.wordpress.org/rest-api/reference/post-revisions/#delete-a-post-revision

**Comment by polushinmk** [comment]
Fixed in PR #39

**Pull request merged**
