### PR TITLE
Fix comments create problem

### PR DESCRIPTION
**Pull request by polushinmk**
#133 add DefaultValueHanling = Ignore to Comments Status property. Hold status is now default
update nuget packages

### CODE REVIEW

**Comment by mickeymarko** [comment]
Thanks, how can  I get this update

**Comment by ThomasPe** [comment]
I'll update the nuget package tonight

**Comment by ThomasPe** [comment]
shouldn't it be Add NullValueHandling to CommentStatus property in the changelog?
I would change it myself but my harddrive just died and I'm waiting for a replacement 🙈

**Comment by polushinmk** [comment]
@ThomasPe done. But it created a merge conflict :(

**Pull request merged**
