### PR TITLE
ListPostsAfter functionality #13

### PR DESCRIPTION
**Pull request by peshos**
Updated QueryBuilder to support "after" search parameter.

### CODE REVIEW

**Comment by ThomasPe** [comment]
looking good, thanks! could you add a few quick tests to the QueryBuilder_Tests?
I know there aren't any yet that actually test if the parameters are working, but that would be a good start. :-)

**Comment by peshos** [comment]
Added a simple test for After parameter.

**Comment by peshos** [comment]
The test are not very thorough but this will depend on the site being used as target. The simple tests I did seem to filter correctly.

**Comment by ThomasPe** [comment]
cool thanks. maybe there could be a test to check for any posts that are older than the time specified.
I'll merge & update nuget tonight.

**Pull request merged**
